### ISSUE TITLE
Add a function for stubborn extremism

### ISSUE THREAD

**Issue by marijnkeijzer** [defSim/defSim#38]
following: http://smaldino.com/wp/wp-content/uploads/2020/06/stubbornextremism_529.pdf

**Comment by dimaba** [comment]
How should we tackle this? 
The 'stubborn extremism' function is basically a weighted linear influence function with smoothing applied based on the agent's current attribute value. There are some differences in implementation compared to our current weighted linear influence function (e.g. no homophily parameter or convergence rate parameter), but in principle that's what it is. 

It feels like we should not implement it as an entirely separate influence function, but allow the application of 'stubbornness' to our existing weighted linear influence function. This would be a conceptual replication of stubborn extremism, but not an exact replication.

I would suggest a separate repository (like the one you set up for the examples) for exact replications of influence functions from specific publications, to which we can add information on the 'defSim native' equivalent. That would allow an investigation of possible differences in results.

**Comment by dimaba** [comment]
https://github.com/marijnkeijzer/defSim/blob/influenceFunctions/defSim/influence_sim/WeightedLinear.py

Rewrote the Weighted Linear influence function to allow modifiers such as smoothing / stubbornness. 
Also separated out components of the influence function to simplify modularity. What do you think?
