### ISSUE TITLE
Check for each module whether it would be compatible with the Networkx DiGraph, or whether substantial changes need to be made in the code

### ISSUE THREAD

**Issue by dimaba** [defSim/defSim#43]
Based on our discussion today, I'm opening this issue to track what changes need to be made to accommodate directed graphs. 

**List of modules to check / which have been checked**
- [x] agents_init: agents_init.py
- [x] agents_init: AttributesInitializer implementations
- [x] dissimilarity_component: dissimilarity_calculator.py
- [x] dissimilarity_component: DissimilarityCalculator implementations
- [x] examples 
- [x] focal_agent_sim: focal_agent_sim.py
- [x] focal_agent_sim: FocalAgentSelector implementations
- [x] influence_sim: influence_sim.py
- [x] influence_sim: InfluenceOperator implementations
- [x] neighbor_selector_sim: neighbor_selector_sim.py
- [x] neighbor_selector_sim: NeighborSelector implementations
- [x] network_evolution_sim: network_evolution_sim.py
- [x] network_evolution_sim: NetworkModifier implementations
- [x] network_init: network_init.py
- [x] tools: OutputMeasures
- [x] tools: CreateOutputTable
- [x] tools: NetworkDistanceUpdater
- [x] tools: ClusterExecutionScript

**Required changes**
Document required changes in comments below. 

**Notes**
- NetworkX methods `nx.Graph.to_directed()` and `nx.DiGraph()` return directed versions of undirected graphs (by deep and shallow copy, respectively). `nx.Graph.to_undirected()` and `nx.Graph()` do the reverse.

**Comment by dimaba** [comment]
**agents_init: agents_init.py**
The `set_categorical_attribute` and `set_continuous_attribute` take `network: nx.Graph` as input, but only manipulate nodes. Accessing nodes should not differ between Graph and DiGraph. Other than that, no parts of NetworkX are referenced.

**Comment by dimaba** [comment]
**agents_init: AttributesInitializer implementations**
_RandomCategoricalInitializer_: only affects nodes, through agents_init.py, which should work with both Graph and DiGraph
_RandomContinuousInitializer_: same
**_CorrelatedContinuousInitializer_**: Initializing correlated continuous attributes by itself is done only using nodes. However, network correlation (e.g. in SimilarityPostprocessor) frequently makes use of network neighbors. In DiGraph, neighbors are only those nodes _to_ which there is a directed tie. This would need to be reworked for directed graphs.

**Comment by marijnkeijzer** [comment]
I gave it a go by simply using a DiGraph in a standard simulation, and this appears to be the only change I have to make: fb8a8526326d43fac2efbf29a43ac2f27cf2b882 (except two workarounds that I implemented quick and dirty now)

Is it really that easy? And do you foresee any problems arising from reversing the call to network.edges[**agent_i, agent_j**]. I don't. As far as I know the order of nodes only matters when we handle directed graphs. Eyeballing output and the results table I do not see any problems.

**Comment by dimaba** [comment]
> I gave it a go by simply using a DiGraph in a standard simulation, and this appears to be the only change I have to make: [fb8a852](https://github.com/marijnkeijzer/defSim/commit/fb8a8526326d43fac2efbf29a43ac2f27cf2b882) (except two workarounds that I implemented quick and dirty now)
> 
> Is it really that easy? And do you foresee any problems arising from reversing the call to network.edges[**agent_i, agent_j**]. I don't. As far as I know the order of nodes only matters when we handle directed graphs. Eyeballing output and the results table I do not see any problems.

Agreed, for undirected graphs the order does not matter so we can use the order we want for digraphs by default



> tools.update_dissimilarity will update the 'dist' variable stored in the edges of the agents (passed as list) who have just been influenced. When graphs are undirected, it doesn't matter whether we call the edge between agents 0 and 1 as [0,1] or as [1,0]. In directed graphs it obviously does. Unfortunately, we need to call both for the influenced agents, because if one of their features changed, this changes the distance on incoming and outgoing ties.
> 
> I believe that the solution implemented in [10ea643](https://github.com/marijnkeijzer/defSim/commit/10ea643923640aa1ee6a596ef669691f4e75501f) works, but it's not the most elegant way. Would it be worthwhile to create different update_dissimilarity functions for Graph and DiGraph types?

Don't think it really matters much if we create different update_dissimilarity functions. There will always have to be a point where we do one thing for graphs and another for digraphs. This seems like a fine place for it, since it doesn't result in any duplicated code. My one suggestion would be to only catch the error you get when you try to call predecessors() on an nx.Graph object (AttributeError?). All other exceptions would be unexpected and so should not be suppressed.
