### ISSUE TITLE
Opinion bounding not applied in bi-directional WeightedLinear influence?

### ISSUE THREAD

**Issue by dimaba** [defSim/defSim#49]
Just noticed that in the Weighted Linear influence function opinions on the influenced feature are limited to [0,1] for influenced agent `neighbor`, but if influence is set to be bi-directional these opinion bounds are not applied to `agent_i`. Is this a bug or just a misunderstanding on my side? 

https://github.com/marijnkeijzer/defSim/blob/33f3980a16fb8990ed0c154b2e5d7485f010d502/defSim/influence_sim/WeightedLinear.py#L108-L117

**Comment by marijnkeijzer** [comment]
83e3eb3cd076fcd4eb6a14e98e1b9411b30ef125
