### ISSUE TITLE
Discuss calculation for Euclidean distance (based on question in todo)

### ISSUE THREAD

**Issue by dimaba** [defSim/defSim#62]
https://github.com/defSim/defSim/blob/fbfcf3a66488d8f55906a2d48f459352e9596f4d/defSim/dissimilarity_component/EuclideanDistance.py#L34

The todo references a change which was made to the Euclidean distance calculation and which was reverted after a failed test.
The change was originally made to normalize the Euclidean distances depending on the number of issues. 
Without the change, Euclidean distance increases with the number of features unless difference on features is 0.

```
>> feature_distances = [1,1,1]
>> np.linalg.norm(feature_distances)
1.7320508075688772
```

With the change, Euclidean distance is constrained to [0,1] and does not change when more features are added with the same distance between agents. (This is why the test failed.)

```
>> feature_distances = [1,1,1]
>> np.linalg.norm(feature_distances) / np.sqrt(len(agent1_attributes))
1.0
```

The desired behavior is up for debate. I would be in favor of constraining to [0,1] because, for example, without it bounded confidence models with higher numbers of features require increasingly broad confidence bounds for influence to occur. See example below for dissimilarity between two agents who are not highly dissimilar on any feature, but nonetheless end up with an overall dissimilarity greater than 1. I think it would make more sense to always have maximally dissimilar agents at dist = 1.

```
feature_distances = [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
np.linalg.norm(feature_distances)
1.0392304845413263
```

**Comment by marijnkeijzer** [comment]
Yes, this makes total sense. I'm always confused by these different distances, their differences in higher dimensions and their implications. Constraining the distance to be between zero and one makes total sense though, and I have convinced myself with pen and paper that this implementation will be okay. 

I would be curious to explore the implications of using different distance metrics for well known models. Perhaps this is something that we can explore in a tutorial script, in a course, or just on a rainy Sunday afternoon.
