### ISSUE TITLE
Replace run_simulation with run (change function name, change references)

### ISSUE THREAD

**Issue by dimaba** [defSim/defSim#74]
Add deprecationwarning to run_simulation, refer to run. Deprecate for 1.0

**Comment by dimaba** [comment]
@marijnkeijzer @antonlaukemper Before I change this, I want to get your feedback on 2 options. We can standardize this in 2 ways:

1) Rename run_simulation to run(). This brings the simulation setup in line with the Experiment setup, and could be extended to initialize_simulation() --> initialize() and run_simulation_step() --> run_step(). 

2) Rename Experiment.run() to run_experiment(). Also standardizes the approach, but the other way around. 

I would suggest option 1, but maybe the additional specificity of option 2 is helpful? What would you prefer?

**Comment by antonlaukemper** [comment]
Imo option 1 is more elegant

**Comment by dimaba** [comment]
Renamed following option 1, added warnings stating that the old names will be removed at or before version 1.0.0
